language: python
sudo: required

python:
- "2.7"
- "3.6"

matrix:
  include:
    - dist: trusty
      env: dist="14.04 LTS trusty"

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq vlan
- util/install.sh -n

install:
- bash -c "if [ `lsb_release -rs` == '14.04' ]; then make codecheck; fi"
- sudo util/install.sh -fnvw

script:
- echo "px import sys; print(sys.version_info)" | sudo mn -v output
- sudo mn --test pingall
- sudo python mininet/test/runner.py -v -quick
- sudo python examples/test/runner.py -v -quick

notifications:
  email:
    on_success: never

# More details: https://docs.travis-ci.com/user/notifications
